name: Compile
description: "Compiles the project"
inputs:
    java-version:
        description: "Java version to compile and test with"
        required: true
        default: "latest"
    gradle-executable:
        description: "The Gradle executable"
        required: true
runs:
    using: composite
    steps:
        -   name: Setup Java
            uses: actions/setup-java@v6
            with:
                distribution: "temurin" # temurin, oracle-openjdk
                java-version: ${{ inputs.java-version }}
                architecture: x64

        -   name: Setup Gradle Cache
            uses: gradle/actions/setup-gradle@v6
            #with:
            #cache-cleanup: on-success # Optionen: 'always', 'never', 'on-success'
            #cache-read-only: true
            #cache-disabled: true

        -   name: Validate Gradle Wrapper
            uses: gradle/actions/wrapper-validation@v6

        -   name: Make Wrapper executable
            if: runner.os != 'Windows'
            #if: contains(matrix.image, 'ubuntu') || contains(matrix.image, 'debian')
            shell: bash
            run: |
                if [ "${{ runner.os }}" = "Windows" ]; then
                   echo "Not necessary on Windows."
                else
                    echo "Make Wrapper executable."
                    chmod 755 gradlew
                fi

        -   name: Build with Gradle
            shell: bash
            # run: ./gradlew --no-daemon build
            run: ${{ inputs.gradle-executable }} --no-daemon build
