# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-gradle

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# https://gradlehero.com/build-gradle-projects-with-github-actions/
# https://github.com/tkgregory/gradle-github-actions-example

# https://docs.github.com/de/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
#
# actions/upload-artifact@v4
# Upload an Artifact to use it in another Job.

# actions/download-artifact@v4
# Download an Artifact from another Job and use it.


name: Java CI with Gradle
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    print-infos:
        name: Printing some Information's
        runs-on: ubuntu-latest
        # runs-on: [ linux, x64 ]

        steps:
            -   run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
            -   run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            -   run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
    build:
        name: Build the Project
        runs-on: ubuntu-latest
        # runs-on: [ linux, x64 ]
        needs: print-infos

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            -   name: List files in the repository
                run: |
                    ls -hal ${{ github.workspace }}
            -   run: echo "This job's status is ${{ job.status }}."

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    java-version: 23
                    distribution: "oracle"
                    architecture: x64

            # Create a persistent Cache for the Jobs.
            #-   name: Setup Gradle
            #    uses: gradle/actions/setup-gradle@v4

            -   name: Make Wrapper executable
                run: chmod 755 gradlew

            -   name: Build with Gradle
                run: ./gradlew build

            -   name: Publish Libs
                uses: actions/upload-artifact@v4
                with:
                    name: Packages
                    path: build/libs/*
                    if-no-files-found: warn
                    retention-days: 30

            -   name: Publish Test Reports
                uses: actions/upload-artifact@v4
                with:
                    name: Test Reports
                    path: build/test-results/**/*.xml
                    if-no-files-found: warn
                    retention-days: 30

            -   name: Publish Reports
                uses: actions/upload-artifact@v4
                with:
                    name: Reports
                    path: build/reports/**/*
                    if-no-files-found: warn
                    retention-days: 30
